contentColumnType: boolean
fieldGroup: c09eaa15-1ea7-44c2-88cc-bc5f5f1728d7
handle: showLeadText
instructions: ''
name: 'Show Lead Text'
searchable: true
settings:
  default: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
