enableVersioning: true
handle: news
name: posts
propagationMethod: all
siteSettings:
  c29e86a0-04a1-4013-9cbc-e4ac7bedbbd5:
    enabledByDefault: true
    hasUrls: true
    template: news/entry
    uriFormat: 'news/{slug}'
type: channel
